[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
rayon = "1.10.0"
reqwest = "0.12.5"
tokio = { version = "1.38.1", features = ["macros", "rt-multi-thread", "sync", "fs"] }

[[bench]]
name = "my_benchmark"
harness = false
